// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRunApp.Models;

namespace MyRunApp.Migrations
{
    [DbContext(typeof(ShoeContext))]
    [Migration("20201006000432_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyRunApp.Models.Color", b =>
                {
                    b.Property<string>("ColorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = "B",
                            Name = "Blue"
                        },
                        new
                        {
                            ColorId = "P",
                            Name = "Pink"
                        },
                        new
                        {
                            ColorId = "G",
                            Name = "Green"
                        },
                        new
                        {
                            ColorId = "O",
                            Name = "Orange"
                        },
                        new
                        {
                            ColorId = "Y",
                            Name = "Yellow"
                        },
                        new
                        {
                            ColorId = "M",
                            Name = "Multi"
                        });
                });

            modelBuilder.Entity("MyRunApp.Models.Shoe", b =>
                {
                    b.Property<int>("ShoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Support")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Use")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoeId");

                    b.HasIndex("ColorId");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            ShoeId = 1,
                            Brand = "Brooks",
                            ColorId = "B",
                            Name = "Ghost 13",
                            Support = "Neutral",
                            Use = "Road Running"
                        },
                        new
                        {
                            ShoeId = 2,
                            Brand = "Hoka",
                            ColorId = "M",
                            Name = "Tennine",
                            Support = "Stability",
                            Use = "Trail Running"
                        },
                        new
                        {
                            ShoeId = 31,
                            Brand = "Saucany",
                            ColorId = "O",
                            Name = "Triumph 17 LE",
                            Support = "Neutral",
                            Use = "Road Running"
                        });
                });

            modelBuilder.Entity("MyRunApp.Models.Shoe", b =>
                {
                    b.HasOne("MyRunApp.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
